application: diggen-aktuellt
version: 1
runtime: python
api_version: 1

builtins:
- remote_api: on
- datastore_admin: on

handlers:
- url: /static
  static_dir: static

- url: /upgrade
  script: upgrade1.py
  login: admin

- url: /ads/.*/admin
  script: admin.py
  login: admin

- url: /billboards/.*/admin
  script: admin.py
  login: admin

- url: .*
  script: main.py
